/** Auto-generated by scripts/bump-version.mjs — do not edit by hand */
export const APP_NAME = "SIGAT";
export const APP_VERSION = "1.0.27";
export const APP_VERSION_LABEL = `${APP_NAME} v${APP_VERSION}`;
