#!/usr/bin/env node
/**
 * Bumps SemVer in package.json, src/lib/version.ts, and docs/PRD.md.
 * Usage: node scripts/bump-version.mjs [patch|minor|major]
 * Default: patch
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const part = (process.argv[2] || "patch").toLowerCase();

if (!["patch", "minor", "major"].includes(part)) {
  console.error(`Uso: node scripts/bump-version.mjs [patch|minor|major]`);
  process.exit(1);
}

const pkgPath = join(root, "package.json");
const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
const current = String(pkg.version || "1.0.0");
const match = current.match(/^(\d+)\.(\d+)\.(\d+)/);

if (!match) {
  console.error(`Versión inválida en package.json: ${current}`);
  process.exit(1);
}

let [, major, minor, patch] = match.map(Number);
if (part === "major") {
  major += 1;
  minor = 0;
  patch = 0;
} else if (part === "minor") {
  minor += 1;
  patch = 0;
} else {
  patch += 1;
}

const next = `${major}.${minor}.${patch}`;
pkg.version = next;
writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);

const versionTs = `/** Auto-generated by scripts/bump-version.mjs — do not edit by hand */
export const APP_NAME = "SIGAT";
export const APP_VERSION = "${next}";
export const APP_VERSION_LABEL = \`\${APP_NAME} v\${APP_VERSION}\`;
`;
writeFileSync(join(root, "src", "lib", "version.ts"), versionTs);

const prdPath = join(root, "docs", "PRD.md");
try {
  let prd = readFileSync(prdPath, "utf8");
  prd = prd.replace(
    /\*\*Versión del sistema:\*\*.*/,
    `**Versión del sistema:** \`${next}\` (auto — ver \`package.json\`)`,
  );
  writeFileSync(prdPath, prd);
} catch {
  // PRD opcional en algunos clones
}

console.log(`Versión: ${current} → ${next}`);
